version: '3'
services:
  frontend:
    container_name: "${COMPOSE_PROJECT_NAME}-frontend"
    image: sergeydevjatov/battleship:frontend
    build: "./frontend"
    ports:
      - 3000:3000
    volumes:
      - "./frontend/src/:/app/src/"

  backend:
    container_name: "${COMPOSE_PROJECT_NAME}-backend"
    image: sergeydevjatov/battleship:backend
    build: "./backend"